module.exports = {
  defaultServerResponse: {
    status: 400,
    message: "",
    body: {},
  },
  productMessage: {
    PRODUCT_CREATED: "Product Created Successfully",
    PRODUCT_FETCHED: "Product Fetched Successfully",
    PRODUCT_UPDATED: "Product Updated Successfully",
    PRODUCT_DELETED: "Product Deleted Successfully",
    PRODUCT_NOT_FOUND: "Product Not Found",
  },
  expenseMessage: {
    EXPENSE_CREATED: "Expense Created Successfully",
    EXPENSE_FETCHED: "Expense Fetched Successfully",
    EXPENSE_UPDATED: "Expense Updated Successfully",
    EXPENSE_DELETED: "Expense Deleted Successfully",
    EXPENSE_NOT_FOUND: "Expense Not Found",
  },
  reportMessage: {
    REPORT_CREATED: "Expense Created Successfully",
    REPORT_FETCHED: "Expense Fetched Successfully",
    REPORT_UPDATED: "Expense Updated Successfully",
    REPORT_DELETED: "Expense Deleted Successfully",
    REPORT_NOT_FOUND: "Expense Not Found",
  },
  paymentMessage: {
    PAYMENT_CREATED: "Expense Created Successfully",
    PAYMENT_FETCHED: "Expense Fetched Successfully",
    PAYMENT_UPDATED: "Expense Updated Successfully",
    PAYMENT_DELETED: "Expense Deleted Successfully",
    PAYMENT_NOT_FOUND: "Expense Not Found",
  },
  passwordMessage: {
    PASSWORD_CREATED: "Expense Created Successfully",
    PASSWORD_FETCHED: "Expense Fetched Successfully",
    PASSWORD_UPDATED: "Expense Updated Successfully",
    PASSWORD_DELETED: "Expense Deleted Successfully",
    PASSWORD_NOT_FOUND: "Expense Not Found",
  },
  orderMessage: {
    ORDER_CREATED: "Expense Created Successfully",
    ORDER_FETCHED: "Expense Fetched Successfully",
    ORDER_UPDATED: "Expense Updated Successfully",
    ORDER_DELETED: "Expense Deleted Successfully",
    ORDER_NOT_FOUND: "Expense Not Found",
  },
  downloadMessage: {
    DOWNLOAD_CREATED: "Expense Created Successfully",
    DOWNLOAD_FETCHED: "Expense Fetched Successfully",
    DOWNLOAD_UPDATED: "Expense Updated Successfully",
    DOWNLOAD_DELETED: "Expense Deleted Successfully",
    DOWNLOAD_NOT_FOUND: "Expense Not Found",
  },
  userMessage: {
    SIGNUP_SUCCESS: "Signup Success",
    LOGIN_SUCCESS: "Login Success",
    DUPLICATE_EMAIL: "User already exist with given email",
    USER_NOT_FOUND: "User not found",
    INVALID_PASSWORD: "Invalid password",
  },
  requestValidationMessage: {
    BAD_REQUEST: "Invalid fields",
    TOKEN_MISSING: "Token missing from header",
  },
  databaseMessage: {
    INVALID_ID: "Invalid Id",
  },
};
